version: '3'

services:
  #MongoDB service
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  #Node API service
  api:
    container_name: node
    build: .
    ports:
     - "127.1.1.17:80:8000"
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: dev

    depends_on:
      - mongo

volumes:
  mongo_db: {}